# Site settings
title: 张立博的博客
SEOTitle: 张立博的博客 | Zhang.Libo Blog
header-img: img/post-bg-desk.jpg
email: zhagnlibo610@outlook.com
description: "Choose from the heart."
keyword: "Blog, 张立博的博客, libozhang, 张立博, java, linux, flutter"
url: "https://libozhang.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/libozhang/libozhang.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Choose from the heart."
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     zhanglibo
# zhihu_username:     zhanglibo610
github_username:    libozhang
#facebook_username:  zhanglibo
jianshu_username:   06d068191419
#twitter_username:   zhanglibo




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: zhanglibo

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 0752c6b324d65fff6686                            #生成的clientID
  clientSecret: 028a17fe14c54fd6d06349d08ba3040abd88a9da    #生成的clientSecret
  repo: libozhang.github.io    #仓库名称
  owner: libozhang    #github用户名
  admin: libozhang
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 5c3c9b0cca44d1ae1acda04aaab94dcc

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: libozhang.github.io               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "简书·张立博",
        href: "http://www.jianshu.com/u/06d068191419"
    }
]
